import { createElement } from '@lwc/engine-dom';
import IDS2DATEPICKER from 'c/iDS2DATEPICKER';

describe('c-i-d-s-2-datepicker', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-i-d-s-2-datepicker', {
            is: IDS2DATEPICKER
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});